using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectedFileSystem.Core.Native
{
  [Flags]
  internal enum PRJ_UPDATE_FAILURE_CAUSES
  {
    PRJ_UPDATE_FAILURE_CAUSE_NONE = BoundConstants.PRJ_UPDATE_FAILURE_CAUSES.PRJ_UPDATE_FAILURE_CAUSE_NONE,
    PRJ_UPDATE_FAILURE_CAUSE_DIRTY_METADATA = BoundConstants.PRJ_UPDATE_FAILURE_CAUSES.PRJ_UPDATE_FAILURE_CAUSE_DIRTY_METADATA,
    PRJ_UPDATE_FAILURE_CAUSE_DIRTY_DATA = BoundConstants.PRJ_UPDATE_FAILURE_CAUSES.PRJ_UPDATE_FAILURE_CAUSE_DIRTY_DATA,
    PRJ_UPDATE_FAILURE_CAUSE_TOMBSTONE = BoundConstants.PRJ_UPDATE_FAILURE_CAUSES.PRJ_UPDATE_FAILURE_CAUSE_TOMBSTONE,
    PRJ_UPDATE_FAILURE_CAUSE_READ_ONLY = BoundConstants.PRJ_UPDATE_FAILURE_CAUSES.PRJ_UPDATE_FAILURE_CAUSE_READ_ONLY,
  }
}
