using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectedFileSystem.Core.Native
{
  [Flags]
  internal enum PRJ_UPDATE_TYPES
  {
    PRJ_UPDATE_NONE = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_NONE,
    PRJ_UPDATE_ALLOW_DIRTY_METADATA = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_ALLOW_DIRTY_METADATA,
    PRJ_UPDATE_ALLOW_DIRTY_DATA = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_ALLOW_DIRTY_DATA,
    PRJ_UPDATE_ALLOW_TOMBSTONE = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_ALLOW_TOMBSTONE,
    PRJ_UPDATE_RESERVED1 = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_RESERVED1,
    PRJ_UPDATE_RESERVED2 = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_RESERVED2,
    PRJ_UPDATE_ALLOW_READ_ONLY = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_ALLOW_READ_ONLY,
    PRJ_UPDATE_MAX_VAL = BoundConstants.PRJ_UPDATE_TYPES.PRJ_UPDATE_MAX_VAL
  }
}
