#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_UPDATE_TYPES
		{
			PRJ_UPDATE_NONE = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_NONE,
			PRJ_UPDATE_ALLOW_DIRTY_METADATA = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_ALLOW_DIRTY_METADATA,
			PRJ_UPDATE_ALLOW_DIRTY_DATA = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_ALLOW_DIRTY_DATA,
			PRJ_UPDATE_ALLOW_TOMBSTONE = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_ALLOW_TOMBSTONE,
			PRJ_UPDATE_RESERVED1 = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_RESERVED1,
			PRJ_UPDATE_RESERVED2 = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_RESERVED2,
			PRJ_UPDATE_ALLOW_READ_ONLY = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_ALLOW_READ_ONLY,
			PRJ_UPDATE_MAX_VAL = ::PRJ_UPDATE_TYPES::PRJ_UPDATE_MAX_VAL
		};
	}
}