#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_UPDATE_FAILURE_CAUSES
		{
			PRJ_UPDATE_FAILURE_CAUSE_NONE = ::PRJ_UPDATE_FAILURE_CAUSES::PRJ_UPDATE_FAILURE_CAUSE_NONE,
			PRJ_UPDATE_FAILURE_CAUSE_DIRTY_METADATA = ::PRJ_UPDATE_FAILURE_CAUSES::PRJ_UPDATE_FAILURE_CAUSE_DIRTY_METADATA,
			PRJ_UPDATE_FAILURE_CAUSE_DIRTY_DATA = ::PRJ_UPDATE_FAILURE_CAUSES::PRJ_UPDATE_FAILURE_CAUSE_DIRTY_DATA,
			PRJ_UPDATE_FAILURE_CAUSE_TOMBSTONE = ::PRJ_UPDATE_FAILURE_CAUSES::PRJ_UPDATE_FAILURE_CAUSE_TOMBSTONE,
			PRJ_UPDATE_FAILURE_CAUSE_READ_ONLY = ::PRJ_UPDATE_FAILURE_CAUSES::PRJ_UPDATE_FAILURE_CAUSE_READ_ONLY,
		};
	}
}