#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_FILE_STATE
		{
			PRJ_FILE_STATE_PLACEHOLDER = ::PRJ_FILE_STATE::PRJ_FILE_STATE_PLACEHOLDER,
			PRJ_FILE_STATE_HYDRATED_PLACEHOLDER = ::PRJ_FILE_STATE::PRJ_FILE_STATE_HYDRATED_PLACEHOLDER,
			PRJ_FILE_STATE_DIRTY_PLACEHOLDER = ::PRJ_FILE_STATE::PRJ_FILE_STATE_DIRTY_PLACEHOLDER,
			PRJ_FILE_STATE_FULL = ::PRJ_FILE_STATE::PRJ_FILE_STATE_FULL,
			PRJ_FILE_STATE_TOMBSTONE = ::PRJ_FILE_STATE::PRJ_FILE_STATE_TOMBSTONE,
		};
	}
}