#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_NOTIFY_TYPES
		{
			PRJ_NOTIFY_NONE = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_NONE,
			PRJ_NOTIFY_SUPPRESS_NOTIFICATIONS = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_SUPPRESS_NOTIFICATIONS,
			PRJ_NOTIFY_FILE_OPENED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_OPENED,
			PRJ_NOTIFY_NEW_FILE_CREATED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_NEW_FILE_CREATED,
			PRJ_NOTIFY_FILE_OVERWRITTEN = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_OVERWRITTEN,
			PRJ_NOTIFY_PRE_DELETE = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_PRE_DELETE,
			PRJ_NOTIFY_PRE_RENAME = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_PRE_RENAME,
			PRJ_NOTIFY_PRE_SET_HARDLINK = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_PRE_SET_HARDLINK,
			PRJ_NOTIFY_FILE_RENAMED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_RENAMED,
			PRJ_NOTIFY_HARDLINK_CREATED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_HARDLINK_CREATED,
			PRJ_NOTIFY_FILE_HANDLE_CLOSED_NO_MODIFICATION = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_HANDLE_CLOSED_NO_MODIFICATION,
			PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_MODIFIED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_MODIFIED,
			PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_DELETED = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_HANDLE_CLOSED_FILE_DELETED,
			PRJ_NOTIFY_FILE_PRE_CONVERT_TO_FULL = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_FILE_PRE_CONVERT_TO_FULL,
			PRJ_NOTIFY_USE_EXISTING_MASK = ::PRJ_NOTIFY_TYPES::PRJ_NOTIFY_USE_EXISTING_MASK
		};
	}
}