#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_NOTIFICATION
		{
			PRJ_NOTIFICATION_FILE_OPENED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_OPENED,
			PRJ_NOTIFICATION_NEW_FILE_CREATED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_NEW_FILE_CREATED,
			PRJ_NOTIFICATION_FILE_OVERWRITTEN = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_OVERWRITTEN,
			PRJ_NOTIFICATION_PRE_DELETE = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_PRE_DELETE,
			PRJ_NOTIFICATION_PRE_RENAME = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_PRE_RENAME,
			PRJ_NOTIFICATION_PRE_SET_HARDLINK = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_PRE_SET_HARDLINK,
			PRJ_NOTIFICATION_FILE_RENAMED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_RENAMED,
			PRJ_NOTIFICATION_HARDLINK_CREATED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_HARDLINK_CREATED,
			PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_NO_MODIFICATION = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_NO_MODIFICATION,
			PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_MODIFIED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_MODIFIED,
			PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_DELETED = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_HANDLE_CLOSED_FILE_DELETED,
			PRJ_NOTIFICATION_FILE_PRE_CONVERT_TO_FULL = ::PRJ_NOTIFICATION::PRJ_NOTIFICATION_FILE_PRE_CONVERT_TO_FULL,
		};
	}
}