#pragma once
#include <projectedfslib.h>
namespace ProjectedFileSystem {
	namespace BoundConstants {
		public enum class PRJ_COMPLETE_COMMAND_TYPE
		{
			PRJ_COMPLETE_COMMAND_TYPE_NOTIFICATION = ::PRJ_COMPLETE_COMMAND_TYPE::PRJ_COMPLETE_COMMAND_TYPE_NOTIFICATION,
			PRJ_COMPLETE_COMMAND_TYPE_ENUMERATION = ::PRJ_COMPLETE_COMMAND_TYPE::PRJ_COMPLETE_COMMAND_TYPE_ENUMERATION
		};
	}
}